version: '3'
services:
  bdserver:
    image: mariadb:10.7.1
    container_name: bdserver
    environment:
      - MYSQL_ROOT_PASSWORD=23!idsidh2838ewu
    volumes:
      - ./db:/var/lib/mysql
      - ./db_config:/etc/mysql/conf.d
    ports:
      - 3333:3306